version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    user: "1000"
    volumes:
      - /opt/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    environment:
      - GF_SERVER_ROOT_URL=http://localhost:3000/grafana
      - GF_SERVER_SERVER_FROM_SUB_PATH=true
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_SECURITY_ALLOW_EMBEDDING=true
    restart: unless-stopped
    container_name: grafana
